version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.7
    steps:
      - checkout
      - run:
          name: The First Step (print notification and list all the files in folder after pull from repo)
          command: |
            echo 'Start deploy'
            ls -al
      - run:
          name: Running in a Unique Container
          command: |
            node -v
  CompleteJobs:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: Approval Complete
          command: |
            echo 'Do work once the approval has completed'

#work flow define
workflows:
  version: 2
  First_workflow:
    jobs:
      - build
      - CompleteJobs:
          requires:
            - build
